### ISSUE TITLE
Then `requestAnimationFrame` was not properly deregistered

### ISSUE THREAD

**Issue by jcold** [RustForWeb/floating-ui#47]
Great work, this saves me a lot of time. I found a bug where `requestAnimationFrame` was not properly deregistered. Looking forward to your fix.

https://github.com/RustForWeb/floating-ui/blob/e85c64fd5bbe477954f69e9a6b2d4dd328c92045/packages/dom/src/auto_update.rs#L384

**Comment by DanielleHuisman** [comment]
Should be addressed by [these commits](https://github.com/RustForWeb/floating-ui/compare/e85c64fd5bbe477954f69e9a6b2d4dd328c92045...1271d378ca82825d452dd4e7067cbaf41e29e108). I will make a release soon, but if you like you can try it directly from Git.

**Comment by jcold** [comment]
Thank you for your quick response. `reobserve_frame` has the same issue. Could you fix that as well?

**Comment by DanielleHuisman** [comment]
As far as I can tell, that code matches the original Floating UI logic of `reobserveFrame` ([source code](https://github.com/floating-ui/floating-ui/blob/master/packages/dom/src/autoUpdate.ts#L162)).

Looking at the code itself, a `cancelAnimationFrame(reobserveFrame);` might be needed in the returned cleanup function. That would cancel the last remaining animation frame. Is that what you are referring to?

**Comment by jcold** [comment]
My use case is to create a cascading menu, as shown in the image below. When quickly moving the mouse back and forth over the primary menu, the secondary menu is created and then destroyed, which easily leads to the error `Resize observer should exist`.

I suspect this is related to Leptos's update mechanism; it might not be using `requestAnimationFrame`. Therefore, when `on_cleanup` is executed and the floating element is destroyed, the browser only begins executing `requestAnimationFrame` tasks afterward. At that point, the resources have already been released, which is likely the root of the issue.

This problem seems to occur only with Leptos + Rust. In JavaScript, resources are handled by garbage collection, and the delay in recovery time generally covers the requestAnimationFrame cycle. Additionally, since methods based on vdom patch typically use requestAnimationFrame, the likelihood of encountering this issue, even without explicitly releasing resources, is very low.

![image](https://github.com/user-attachments/assets/bb7477d2-721b-4361-88cc-f8fd62951fc1)

**Comment by DanielleHuisman** [comment]
Could you try the [`fix/resize-observer` branch](https://github.com/RustForWeb/floating-ui/tree/fix/resize-observer)? If that doesn't help, I will replace the `expect` calls in the resize observer closure with `if let Some()`.

**Comment by jcold** [comment]
This version works, and the above two problems no longer occur.

As Rust+WASM becomes more and more popular, more people will use it. This is a great library, and thanks to people like you for contributing.

**Comment by DanielleHuisman** [comment]
Released in [v0.1.2](https://github.com/RustForWeb/floating-ui/releases/tag/v0.1.2).
